SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS `pia` DEFAULT CHARACTER SET utf8 ;
USE `test_hf` ;

-- -----------------------------------------------------
-- Table `test_hf`.`video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test_hf`.`video` (
  `title` VARCHAR(100) NOT NULL,
  `price` INT,
  PRIMARY KEY (`title`))
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

